---

name: screenload
adopt-info: screenload
base: core20
summary: Powerful yet simple to use screenshot software
description: |
  A powerful open source screenshot and annotation tool for Linux, ScreenLoad
  has a varied set of markup tools available, which include Freehand drawing,
  Lines, Arrows, Boxes, Circles, Highlighting, Blur. Additionally, you can
  customise the color, size and/or thickness of many of these image annotation
  tools.
grade: stable  # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
#confinement: devmode  # use 'strict' once you have the right plugs and slot
compression: lzo
architectures:
  - build-on: amd64

apps:
  screenload:
    command: usr/local/bin/screenload
    desktop: usr/local/share/applications/ru.screenload.ScreenLoad.desktop
    extensions:
      - kde-neon
    environment:
      DISABLE_WAYLAND: 1
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      QT_QPA_PLATFORMTHEME: gtk3
    slots: [dbus-screenload]
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7

parts:
  screenload:
    build-snaps:
      - kde-frameworks-5-qt-5-15-core20
    source: https://github.com/screenload-org/screenload.git
    plugin: cmake
    cmake-parameters:
       - -DSCREENLOAD_ICON=/snap/screenload/current/usr/local/share/icons/hicolor/scalable/apps/screenload.svg
       # This cannot be enabled until the KF5 toolkit in the snap is updated
       #- -DUSE_WAYLAND_CLIPBOARD=1
    source-type: git
    override-pull: |
      snapcraftctl pull
      # remove release candidates
      last_committed_tag="$(git tag -l --sort=-v:refname | grep -v rc | head -1)"
      git_revno="$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)"
      git_hash="$(git rev-parse --short HEAD)"
      snapcraftctl set-version "${last_committed_tag}+git${git_revno}.${git_hash}"
    override-build: |
      snapcraftctl build
      # Correct the Icon path
      sed -i 's|^Exec=screenload|Exec=/snap/bin/ru.screenload.ScreenLoad|' ${SNAPCRAFT_PART_INSTALL}/usr/local/share/applications/ru.screenload.ScreenLoad.desktop
      sed -i 's|^Icon=.*|Icon=${SNAP}/usr/local/share/icons/hicolor/scalable/apps/ru.screenload.ScreenLoad.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/local/share/applications/ru.screenload.ScreenLoad.desktop
      sed -i 's/^\(Name\(\[.\+\]\)\?=.*\)$/\1 (Snappy Edition)/g' ${SNAPCRAFT_PART_INSTALL}/usr/local/share/applications/ru.screenload.ScreenLoad.desktop
    build-packages:
      - g++
      - make
      - qt5-default
      - git
    stage-packages:
      - dbus-x11
      - libgtk2.0-0
      - openssl
      - ca-certificates
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
slots:
  # Depending on in which environment we're running we either need
  # to use the system or session DBus so we also need to have one
  # slot for each.
  dbus-screenload:
    interface: dbus
    bus: session
    name: ru.screenload.ScreenLoad
