chmod 755 usr/share/applications/
chmod 755 usr/share/bash-completion/
chmod 755 usr/share/bash-completion/completions/
chmod 755 usr/share/dbus-1/
chmod 755 usr/share/dbus-1/interfaces/
chmod 755 usr/share/dbus-1/services/
chmod 755 usr/share/doc/
chmod 755 usr/share/doc/screenload/
chmod 755 usr/share/icons/
chmod 755 usr/share/icons/hicolor/
chmod 755 usr/share/icons/hicolor/128x128/
chmod 755 usr/share/icons/hicolor/128x128/apps/
chmod 755 usr/share/icons/hicolor/48x48/
chmod 755 usr/share/icons/hicolor/48x48/apps/
chmod 755 usr/share/icons/hicolor/scalable/
chmod 755 usr/share/icons/hicolor/scalable/apps/
chmod 755 usr/share/metainfo/
chmod 755 usr/share/screenload/
chmod 755 usr/share/screenload/translations/
chmod 755 usr/share/zsh/
chmod 755 usr/share/zsh/site-functions/

chmod 644 usr/share/dbus-1/interfaces/ru.screenload.ScreenLoad.xml
chmod 644 usr/share/dbus-1/services/ru.screenload.ScreenLoad.service
chmod 644 usr/share/doc/screenload/README.md.gz
chmod 644 usr/share/doc/screenload/changelog.Debian.gz
chmod 644 usr/share/doc/screenload/copyright
chmod 644 usr/share/icons/hicolor/128x128/apps/ru.screenload.ScreenLoad.png
chmod 644 usr/share/icons/hicolor/128x128/apps/screenload.png
chmod 644 usr/share/icons/hicolor/48x48/apps/ru.screenload.ScreenLoad.png
chmod 644 usr/share/icons/hicolor/48x48/apps/screenload.png
chmod 644 usr/share/icons/hicolor/scalable/apps/ru.screenload.ScreenLoad.svg
chmod 644 usr/share/icons/hicolor/scalable/apps/screenload.svg
chmod 644 usr/share/metainfo/ru.screenload.ScreenLoad.metainfo.xml
chmod 644 usr/share/screenload/translations/Internationalization_bg.qm
chmod 644 usr/share/screenload/translations/Internationalization_ca.qm
chmod 644 usr/share/screenload/translations/Internationalization_cs.qm
chmod 644 usr/share/screenload/translations/Internationalization_de_DE.qm
chmod 644 usr/share/screenload/translations/Internationalization_el.qm
chmod 644 usr/share/screenload/translations/Internationalization_es.qm
chmod 644 usr/share/screenload/translations/Internationalization_eu.qm
chmod 644 usr/share/screenload/translations/Internationalization_fa.qm
chmod 644 usr/share/screenload/translations/Internationalization_fi.qm
chmod 644 usr/share/screenload/translations/Internationalization_fr.qm
chmod 644 usr/share/screenload/translations/Internationalization_gl.qm
chmod 644 usr/share/screenload/translations/Internationalization_grc.qm
chmod 644 usr/share/screenload/translations/Internationalization_he.qm
chmod 644 usr/share/screenload/translations/Internationalization_hu.qm
chmod 644 usr/share/screenload/translations/Internationalization_id.qm
chmod 644 usr/share/screenload/translations/Internationalization_it_IT.qm
chmod 644 usr/share/screenload/translations/Internationalization_ja.qm
chmod 644 usr/share/screenload/translations/Internationalization_ka.qm
chmod 644 usr/share/screenload/translations/Internationalization_ko.qm
chmod 644 usr/share/screenload/translations/Internationalization_nb_NO.qm
chmod 644 usr/share/screenload/translations/Internationalization_nl.qm
chmod 644 usr/share/screenload/translations/Internationalization_nl_NL.qm
chmod 644 usr/share/screenload/translations/Internationalization_pl.qm
chmod 644 usr/share/screenload/translations/Internationalization_pt_BR.qm
chmod 644 usr/share/screenload/translations/Internationalization_ru.qm
chmod 644 usr/share/screenload/translations/Internationalization_sk.qm
chmod 644 usr/share/screenload/translations/Internationalization_sr_SP.qm
chmod 644 usr/share/screenload/translations/Internationalization_sv_SE.qm
chmod 644 usr/share/screenload/translations/Internationalization_tr.qm
chmod 644 usr/share/screenload/translations/Internationalization_uk.qm
chmod 644 usr/share/screenload/translations/Internationalization_vi.qm
chmod 644 usr/share/screenload/translations/Internationalization_zh_CN.qm
chmod 644 usr/share/screenload/translations/Internationalization_zh_HK.qm
chmod 644 usr/share/screenload/translations/Internationalization_zh_TW.qm
chmod 644 usr/share/zsh/site-functions/_screenload